#return = ""     # Don't write the return value here - Because the return value is the Struct data

# [NOTE]: Each `revealed` data (i.e. `revealName`) should be written in `"Boolean"` type. But, it should be written in a string number (True: `"0"` / False: `"1"`)
name = ""
walletAddress = "<EOA /or SmartContractWallet addresss of a Health Data Provider>"
height = ""
weight = ""
age = ""
gender = ""
race_type = ""
blood_type = ""
blood_pressure_systolic = ""
blood_pressure_diastolic = ""
heart_rate = ""
average_hours_of_sleep = ""
revealName = ""
revealWalletAddress = ""
revealAge = ""
revealGender = ""
revealHeight = ""
revealWeight = ""
revealRaceType = ""
revealBloodType = ""
revealBloodPressureSystolic = ""
revealBloodPressureDiastolic = ""
revealHeartRate = ""
revealAverageHoursOfSleep = ""