#return = ""     # Don't write the return value here - Because the return value is the Struct data

# [NOTE]: Input of "Boolean" type should be write in number (True: "0" / False: "1")
name = ""
walletAddress = ""
height = ""
weight = ""
age = ""
gender = ""
race_type = ""
blood_type = ""
blood_pressure = ""
heart_rate = ""
average_hours_of_sleep = ""
revealProviderId = ""
revealName = ""
revealWalletAddress = ""
revealAge = ""
revealGender = ""
revealHeight = ""
revealWeight = ""
revealRaceType = ""
revealBloodType = ""
revealBloodPressure = ""
revealHeartRate = ""
revealAverageHoursOfSleep = ""